version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies
      - cd react-app
      - npm install
  build:
    commands:
      - echo Running tests
      - npm test -- --coverage
      - echo Building production artifacts
      - npm run build
  post_build:
    commands:
      - echo "Build completed"

artifacts:
  base-directory: react-app/build
  files:
    - '**/*'
